import type { TennisMatch } from "@/lib/tennis/matches";

// ── ZONE 27 · 網球真實賽程資料(2026-06-24/25 · 從台灣運彩 curate · 名字一字不改)──────
// 純資料檔(邏輯在 matches.ts)。 id = 運彩場次編號。 rank = 球員辨識後查「現時官方世界排名」
// (估計種子分來源 · top-60 走官方榜核對、長尾用辨識排名)· 換算引擎勝率。
// 🔴 誠實鐵律落地:
//   · 進行中(live)→ 不開盤(引擎只做賽前)。
//   · 球員認不出 / 排名查不到 → rank null + confidence "low" → 自動「覆蓋建置中」。
//   · 剛傷退復出(德雷珀 #160 / 季米特洛夫 #170 / 安德列斯庫 出榜外)→ 排名嚴重失真,
//     引擎不靠失真排名硬猜 → 標 note,不開盤(這正是「引擎有盲點、你的判斷值錢」)。
// 這些多為溫網會外賽 + 草地熱身賽,球員多在 #90–#260。 結算後 Tim 補 finalResult(Wave 2)。
// ─────────────────────────────────────────────────────

export const TENNIS_DRAW: TennisMatch[] = [
  // ── 2026-06-29 溫布頓網球公開賽 R1(草地 · Tim 運彩截圖 curate · 名字一字不改)──────────────
  //   🔴 ID 用「日期標籤」tn-0629-XXXX:運彩場次編號每週重複使用,2013/2024/2050… 早被上週網球占用,
  //      直接用會撞號破 build · 故這批用 6/29 日期前綴保證唯一(auto-settle 走英文名不靠 id · 不受影響)。
  //   球員排名 = 編輯估計值(背景查證 2026 年中 ATP/WTA · 非官方數據)· 認不出 / 傷癒失真 / 名字對不上
  //      → rank null + confidence low → 引擎不硬開盤、照樣可押(你的判斷比引擎值錢)。 結算 Tim 賽後 curate。
  // ── WTA ──
  { id: "tn-0629-2013", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "米卡.斯托伊薩夫列維奇", en: "Mika Stojsavljevic", rank: 255, confidence: "medium" },
    b: { zh: "B.班西琪", en: "Belinda Bencic", rank: 11, confidence: "high" } },
  { id: "tn-0629-2014", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "M.赫瓦林斯卡", en: "Maja Chwalinska", rank: 21, confidence: "high" },
    b: { zh: "瑪南查雅.莎晚秋", en: "Mananchaya Sawangkaew", rank: 170, confidence: "medium" } },
  { id: "tn-0629-2020", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "伊娃.約維奇", en: "Iva Jovic", rank: 18, confidence: "high" },
    b: { zh: "賈奎琳.克莉絲汀", en: "Jaqueline Cristian", rank: 38, confidence: "high" } },
  { id: "tn-0629-2012", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    note: "托莫這個運彩簡稱我們對不到唯一一位選手(Tomljanovic / Tomova 都有可能)—— 認不準就不硬開,照樣可押。",
    a: { zh: "吉梅內斯卡辛茲瓦", en: "Victoria Jimenez Kasintseva", rank: 90, confidence: "medium" },
    b: { zh: "托莫", en: "?", rank: null, confidence: "low" } },
  { id: "tn-0629-2027", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:10",
    a: { zh: "柯西亞瑞托", en: "Elisabetta Cocciaretto", rank: 38, confidence: "high" },
    b: { zh: "王欣瑜", en: "Wang Xinyu", rank: 32, confidence: "high" } },
  { id: "tn-0629-2030", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:10",
    a: { zh: "Z.桑梅斯", en: "Zeynep Sonmez", rank: 54, confidence: "high" },
    b: { zh: "李安", en: "Ann Li", rank: 29, confidence: "high" } },
  { id: "tn-0629-2033", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    a: { zh: "艾莉西亞.杜德尼", en: "Alicia Dudeney", rank: 248, confidence: "medium" },
    b: { zh: "阿莉西亞.帕克斯", en: "Alycia Parks", rank: 80, confidence: "high" } },
  { id: "tn-0629-2032", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    a: { zh: "哈里特.達特", en: "Harriet Dart", rank: 160, confidence: "medium" },
    b: { zh: "奧斯塔佩科", en: "Jelena Ostapenko", rank: 30, confidence: "high" } },
  { id: "tn-0629-2034", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    note: "安德列斯庫剛傷癒復出 · 排名嚴重失真 · 引擎不靠失真排名硬猜 —— 這場你的判斷比引擎值錢。",
    a: { zh: "張帥", en: "Zhang Shuai", rank: 65, confidence: "medium" },
    b: { zh: "比安卡.安德列斯庫", en: "Bianca Andreescu", rank: null, confidence: "low" } },
  { id: "tn-0629-2042", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 20:00",
    a: { zh: "艾瑪.拉杜卡努", en: "Emma Raducanu", rank: 28, confidence: "high" },
    b: { zh: "安東尼婭.魯茲奇", en: "Antonia Ruzic", rank: 58, confidence: "high" } },
  { id: "tn-0629-2041", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 20:00",
    a: { zh: "T.馬莉亞", en: "Tatjana Maria", rank: 53, confidence: "high" },
    b: { zh: "普汀塞娃", en: "Yulia Putintseva", rank: 85, confidence: "medium" } },
  { id: "tn-0629-2053", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:20",
    note: "劉婧文這個運彩名我們對不準是哪一位(劉婧文 / Claire Liu 易混)—— 認不準就不硬開,照樣可押。",
    a: { zh: "H.范德溫克爾", en: "Hanne Vandewinkel", rank: 92, confidence: "medium" },
    b: { zh: "劉婧文", en: "?", rank: null, confidence: "low" } },
  { id: "tn-0629-2055", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:20",
    a: { zh: "N.巴爾通科娃", en: "Nikola Bartunkova", rank: 50, confidence: "high" },
    b: { zh: "佩頓.斯特恩絲", en: "Peyton Stearns", rank: 40, confidence: "high" } },
  { id: "tn-0629-2054", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:20",
    a: { zh: "凱斯勒.麥卡特尼", en: "McCartney Kessler", rank: 62, confidence: "high" },
    b: { zh: "O.奧利尼科娃", en: "Oleksandra Oliynykova", rank: 49, confidence: "high" } },
  { id: "tn-0629-2052", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:20",
    // en 用她巡迴賽登錄名 Mimi Xu(ESPN/WTA 一律這個 · 原寫 Mingge Xu 對不上鏡像 → 賽果永遠配不到)。
    a: { zh: "卡薩金娜", en: "Daria Kasatkina", rank: 68, confidence: "medium" },
    b: { zh: "徐銘格", en: "Mimi Xu", rank: 248, confidence: "medium" } },
  { id: "tn-0629-2056", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:20",
    a: { zh: "莉莉.塔格", en: "Lilli Tagger", rank: 90, confidence: "high" },
    b: { zh: "L.塔拉魯娃", en: "Lanlana Tararudee", rank: 100, confidence: "medium" } },
  { id: "tn-0629-2058", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:30",
    a: { zh: "A.扎哈諾娃", en: "Anastasia Zakharova", rank: 85, confidence: "medium" },
    b: { zh: "卡蘿莉斯.穆霍娃", en: "Karolina Muchova", rank: 10, confidence: "high" } },
  // ── ATP ──
  { id: "tn-0629-2024", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "卡雷諾-布斯塔", en: "Pablo Carreno Busta", rank: 90, confidence: "medium" },
    b: { zh: "沙波瓦羅夫", en: "Denis Shapovalov", rank: 41, confidence: "high" } },
  { id: "tn-0629-2023", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "伊格納西奧.布斯", en: "Ignacio Buse", rank: 31, confidence: "high" },
    b: { zh: "埃米利奧.納瓦", en: "Emilio Nava", rank: 90, confidence: "medium" } },
  { id: "tn-0629-2018", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "法索維克斯", en: "Marton Fucsovics", rank: 56, confidence: "high" },
    b: { zh: "盧卡.范阿斯切", en: "Luca Van Assche", rank: 85, confidence: "medium" } },
  { id: "tn-0629-2019", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "勒納.錢", en: "Learner Tien", rank: 17, confidence: "high" },
    b: { zh: "D.斯夫爾奇納", en: "Dalibor Svrcina", rank: 110, confidence: "medium" } },
  { id: "tn-0629-2017", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "小馬丁.達姆", en: "Martin Damm Jr.", rank: 115, confidence: "medium" },
    b: { zh: "圖盧傑利蒂", en: "Marco Trungelliti", rank: 85, confidence: "medium" } },
  { id: "tn-0629-2025", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "J.布魯克斯比", en: "Jenson Brooksby", rank: 90, confidence: "medium" },
    b: { zh: "亞歷山大.武基奇", en: "Aleksandar Vukic", rank: 95, confidence: "medium" } },
  { id: "tn-0629-2026", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    note: "馬克斯.貝爾這個運彩名對不到唯一一位 ATP 正賽選手 —— 認不出就不硬開,照樣可押。",
    a: { zh: "馬克斯.貝爾", en: "?", rank: null, confidence: "low" },
    b: { zh: "望月慎太郎", en: "Shintaro Mochizuki", rank: 125, confidence: "high" } },
  { id: "tn-0629-2016", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "范德贊舒爾普", en: "Botic van de Zandschulp", rank: 55, confidence: "high" },
    b: { zh: "A.科瓦塞維奇", en: "Aleksandar Kovacevic", rank: 85, confidence: "medium" } },
  { id: "tn-0629-2015", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "羅曼.薩菲烏林", en: "Roman Safiullin", rank: 80, confidence: "medium" },
    b: { zh: "魯布列夫", en: "Andrey Rublev", rank: 13, confidence: "high" } },
  { id: "tn-0629-2022", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 18:00",
    a: { zh: "菲利克斯.吉爾", en: "Felix Gill", rank: 220, confidence: "medium" },
    b: { zh: "拉斐爾.霍達爾", en: "Rafael Jodar", rank: 23, confidence: "high" } },
  { id: "tn-0629-2028", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:10",
    a: { zh: "諾里", en: "Cameron Norrie", rank: 26, confidence: "high" },
    b: { zh: "邁克爾.鄭", en: "Michael Zheng", rank: 143, confidence: "high" } },
  { id: "tn-0629-2029", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:10",
    a: { zh: "奧利佛.塔維特", en: "Oliver Tarvet", rank: 160, confidence: "medium" },
    b: { zh: "亞瑟.瑞德克內希", en: "Arthur Rinderknech", rank: 28, confidence: "high" } },
  { id: "tn-0629-2038", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    note: "胡卡奇這個運彩名我們的查證對到了不一致的人(Hurkacz / Hijikata)—— 認不準就不硬開,照樣可押。",
    a: { zh: "胡卡奇", en: "?", rank: null, confidence: "low" },
    b: { zh: "魯德", en: "Casper Ruud", rank: 12, confidence: "high" } },
  { id: "tn-0629-2039", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    a: { zh: "奧夫納", en: "Sebastian Ofner", rank: 90, confidence: "medium" },
    b: { zh: "H.梅傑多維奇", en: "Hamad Medjedovic", rank: 81, confidence: "high" } },
  { id: "tn-0629-2037", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    a: { zh: "崔斯坦.博耶", en: "Tristan Boyer", rank: 110, confidence: "medium" },
    b: { zh: "努諾.博爾赫斯", en: "Nuno Borges", rank: 54, confidence: "high" } },
  { id: "tn-0629-2036", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    a: { zh: "斯特凡諾斯.西西帕斯", en: "Stefanos Tsitsipas", rank: 80, confidence: "high" },
    b: { zh: "胡戈.加斯東", en: "Hugo Gaston", rank: 90, confidence: "medium" } },
  { id: "tn-0629-2040", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    a: { zh: "馬丁.蘭達盧塞", en: "Martin Landaluce", rank: 67, confidence: "high" },
    b: { zh: "權純朗", en: "Soonwoo Kwon", rank: 110, confidence: "medium" } },
  { id: "tn-0629-2035", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 19:40",
    a: { zh: "丹尼爾.梅里達", en: "Daniel Merida", rank: 86, confidence: "high" },
    b: { zh: "C.烏戈卡拉貝利", en: "Camilo Ugo Carabelli", rank: 68, confidence: "high" } },
  { id: "tn-0629-2043", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 20:20",
    a: { zh: "迪諾.普里茲米奇", en: "Dino Prizmic", rank: 71, confidence: "high" },
    b: { zh: "當當.沃爾頓", en: "Adam Walton", rank: 95, confidence: "medium" } },
  { id: "tn-0629-2045", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 20:50",
    note: "瓦列霍是年輕新秀、排名波動大、查證信心低 —— 不硬開,照樣可押。",
    a: { zh: "尼古拉斯.梅希亞", en: "Nicolas Mejia", rank: 135, confidence: "medium" },
    b: { zh: "A.D.瓦列霍", en: "Adolfo Daniel Vallejo", rank: null, confidence: "low" } },
  { id: "tn-0629-2046", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 20:50",
    a: { zh: "若奧.豐塞卡", en: "Joao Fonseca", rank: 28, confidence: "high" },
    b: { zh: "羅伯托-包蒂斯塔-阿古特", en: "Roberto Bautista Agut", rank: 90, confidence: "medium" } },
  { id: "tn-0629-2047", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 20:50",
    a: { zh: "法比安.馬羅森", en: "Fabian Marozsan", rank: 55, confidence: "high" },
    b: { zh: "奧古斯丁.蒂蘭特", en: "Thiago Agustin Tirante", rank: 52, confidence: "high" } },
  { id: "tn-0629-2051", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:10",
    note: "史札夫這個運彩名我們對不到唯一一位 ATP 正賽選手 —— 認不出就不硬開,照樣可押。",
    a: { zh: "塞巴斯蒂安.貝斯", en: "Sebastian Baez", rank: 39, confidence: "high" },
    b: { zh: "史札夫", en: "?", rank: null, confidence: "low" } },
  { id: "tn-0629-2050", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:10",
    a: { zh: "梅德維夫", en: "Daniil Medvedev", rank: 7, confidence: "high" },
    b: { zh: "馬林.契利奇", en: "Marin Cilic", rank: 60, confidence: "medium" } },
  { id: "tn-0629-2060", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:30",
    a: { zh: "盧西亞諾.達德里", en: "Luciano Darderi", rank: 16, confidence: "high" },
    b: { zh: "伊森.奎因", en: "Ethan Quinn", rank: 55, confidence: "high" } },
  { id: "tn-0629-2061", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/29 21:30",
    a: { zh: "J.M.塞倫多洛", en: "Juan Manuel Cerundolo", rank: 95, confidence: "medium" },
    b: { zh: "達比多維奇", en: "Alejandro Davidovich Fokina", rank: 40, confidence: "high" } },

  // ── ATP · 伊斯特本公開賽(草地)─────────────────────────────
  { id: "tn-2061", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/24",
    a: { zh: "J.布魯克斯比", en: "Jenson Brooksby", rank: 67, confidence: "high" },
    b: { zh: "U.亨伯特", en: "Ugo Humbert", rank: 30, confidence: "high" },
    finalResult: { winner: "b", score: "6-3 6-2" } },
  { id: "tn-2180", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/24 22:30",
    a: { zh: "湯瑪斯.馬丁.艾切維利", en: "Tomas Martin Etcheverry", rank: 32, confidence: "high" },
    b: { zh: "G.迪亞洛", en: "Gabriel Diallo", rank: 91, confidence: "high" },
    finalResult: { winner: "b", score: "6-7 6-3 6-2" } },
  { id: "tn-2174", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/24 22:40",
    note: "J.德雷珀剛傷退復出 · 排名(#160)嚴重失真 · 引擎不靠失真排名硬猜 —— 這場你的判斷比引擎值錢。",
    a: { zh: "傑克.平寧頓-瓊斯", en: "Jack Pinnington Jones", rank: 145, confidence: "high" },
    b: { zh: "J.德雷珀", en: "Jack Draper", rank: null, confidence: "low" },
    finalResult: { winner: "b", score: "7-5 6-4" } },

  // ── ATP · 溫布頓網球公開賽(草地 · 多為會外賽)─────────────────
  { id: "tn-2141", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "即將開始",
    a: { zh: "基默.科佩揚斯", en: "Kimmer Coppejans", rank: 212, confidence: "medium" },
    b: { zh: "羅曼.薩菲烏林", en: "Roman Safiullin", rank: 141, confidence: "medium" },
    finalResult: { winner: "b", score: "7-6 7-5" } },
  { id: "tn-2158", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "13 分鐘後開始",
    a: { zh: "蒂莫菲.史卡托夫", en: "Timofey Skatov", rank: 189, confidence: "medium" },
    b: { zh: "埃利亞斯.伊梅爾", en: "Elias Ymer", rank: 191, confidence: "medium" },
    finalResult: { winner: "a", score: "6-4 6-1" } },
  { id: "tn-2138", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "18 分鐘後開始",
    a: { zh: "盧卡.帕夫洛維奇", en: "Luka Pavlovic", rank: 218, confidence: "high" },
    b: { zh: "J.法里亞", en: "Jaime Faria", rank: 97, confidence: "high" },
    finalResult: { winner: "b", score: "6-4 6-4" } },
  { id: "tn-2140", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "18 分鐘後開始",
    a: { zh: "邁克爾.鄭", en: "Michael Zheng", rank: 145, confidence: "medium" },
    b: { zh: "捷雷", en: "Laslo Djere", rank: 205, confidence: "medium" },
    finalResult: { winner: "a", score: "7-5 6-3" } },
  { id: "tn-2156", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "18 分鐘後開始",
    a: { zh: "杜尚.拉約維奇", en: "Dusan Lajovic", rank: 131, confidence: "high" },
    b: { zh: "克里斯.羅德施", en: "Chris Rodesch", rank: 139, confidence: "high" },
    finalResult: { winner: "a", score: "6-2 6-4" } },
  { id: "tn-2166", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "18 分鐘後開始",
    a: { zh: "莫埃茲.埃查爾吉", en: "Moez Echargui", rank: 140, confidence: "high" },
    b: { zh: "基根.史密斯", en: "Keegan Smith", rank: 244, confidence: "high" },
    finalResult: { winner: "a", score: "6-4 3-6 7-6" } },
  { id: "tn-2165", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "23 分鐘後開始",
    a: { zh: "亞瑟.蓋亞", en: "Arthur Gea", rank: 135, confidence: "high" },
    b: { zh: "權純雨", en: "Kwon Soon-woo", rank: 202, confidence: "medium" },
    finalResult: { winner: "b", score: "5-7 6-3 6-4" } },
  { id: "tn-2159", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "27 分鐘後開始",
    a: { zh: "奧托.維爾塔寧", en: "Otto Virtanen", rank: 130, confidence: "high" },
    b: { zh: "盧卡.納迪", en: "Luca Nardi", rank: 151, confidence: "medium" },
    finalResult: { winner: "a", score: "6-4 6-4" } },
  { id: "tn-2167", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "27 分鐘後開始",
    a: { zh: "哈羅德.馬約", en: "Harold Mayot", rank: 214, confidence: "medium" },
    b: { zh: "亞歷杭德羅.莫爾-卡納斯", en: "Alejandro Moro Canas", rank: 233, confidence: "high" },
    finalResult: { winner: "b", score: "6-3 7-6" } },
  { id: "tn-2178", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "27 分鐘後開始",
    a: { zh: "亨利.塞爾", en: "Henry Searle", rank: 263, confidence: "high" },
    b: { zh: "維利烏斯.高巴斯", en: "Vilius Gaubas", rank: 105, confidence: "high" },
    finalResult: { winner: "b", score: "7-6 7-6" } },
  { id: "tn-2164", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:40",
    a: { zh: "基里安.雅凱", en: "Kyrian Jacquet", rank: 146, confidence: "high" },
    b: { zh: "安德里亞.蓋里耶里", en: "Andrea Guerrieri", rank: 229, confidence: "high" },
    finalResult: { winner: "a", score: "7-6 6-4" } },
  { id: "tn-2145", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:50",
    a: { zh: "坂本怜", en: "Rei Sakamoto", rank: 148, confidence: "high" },
    b: { zh: "阿齊茲.杜加茲", en: "Aziz Dougaz", rank: null, confidence: "low" },
    finalResult: { winner: "a", score: "6-4 6-4" } },
  { id: "tn-2172", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:20",
    a: { zh: "馬特.多迪格", en: "Matej Dodig", rank: 201, confidence: "high" },
    b: { zh: "布德科夫-基埃爾", en: "Nicolai Budkov Kjaer", rank: 140, confidence: "medium" },
    finalResult: { winner: "b", score: "6-2 7-6" } },
  { id: "tn-2160", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:45",
    a: { zh: "A.佩萊格里諾", en: "Andrea Pellegrino", rank: 109, confidence: "high" },
    b: { zh: "崔斯坦.博耶", en: "Tristan Boyer", rank: 210, confidence: "medium" },
    finalResult: { winner: "b", score: "6-2 6-1" } },
  { id: "tn-2161", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:45",
    a: { zh: "馬丁-蒂芬", en: "Pol Martin Tiffon", rank: 220, confidence: "medium" },
    b: { zh: "拉馬斯魯伊斯", en: "Pablo Llamas Ruiz", rank: 119, confidence: "high" },
    finalResult: { winner: "b", score: "6-4 6-2" } },

  // ── ATP · 馬約卡公開賽(草地)─────────────────────────────
  { id: "tn-2190", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/24 23:30",
    note: "季米特洛夫剛傷退復出(外卡)· 排名(#170)嚴重失真 · 引擎不靠失真排名硬猜 —— 你的判斷值錢。",
    a: { zh: "季米特洛夫", en: "Grigor Dimitrov", rank: null, confidence: "low" },
    b: { zh: "阿卜杜拉.謝爾巴耶夫", en: "Abdullah Shelbayh", rank: 259, confidence: "medium" } },
  { id: "tn-2063", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/25 17:00",
    a: { zh: "維特.科普里瓦", en: "Vit Kopriva", rank: 68, confidence: "medium" },
    b: { zh: "伊森.奎因", en: "Ethan Quinn", rank: 63, confidence: "medium" } },
  { id: "tn-2054", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/25 18:10",
    a: { zh: "努諾.博爾赫斯", en: "Nuno Borges", rank: 53, confidence: "high" },
    b: { zh: "盧西亞諾.達德里", en: "Luciano Darderi", rank: 16, confidence: "high" } },
  { id: "tn-2055", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/25 20:30",
    a: { zh: "法比安.馬羅森", en: "Fabian Marozsan", rank: 62, confidence: "high" },
    b: { zh: "凱曼諾維奇", en: "Miomir Kecmanovic", rank: 51, confidence: "high" } },

  // ── WTA · 溫布頓網球公開賽(草地 · 多為會外賽)─────────────────
  { id: "tn-2016", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "22 分鐘後開始",
    a: { zh: "埃默生.瓊斯", en: "Emerson Jones", rank: 129, confidence: "medium" },
    b: { zh: "A.加薩諾娃", en: "Anastasia Gasanova", rank: 210, confidence: "high" } },
  { id: "tn-2194", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:30",
    a: { zh: "莉娜.喬爾切斯卡", en: "Lina Gjorcheska", rank: 188, confidence: "medium" },
    b: { zh: "弗朗西斯卡.豪爾赫", en: "Francisca Jorge", rank: 200, confidence: "medium" } },
  { id: "tn-2007", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:35",
    a: { zh: "日比野菜緒", en: "Nao Hibino", rank: 171, confidence: "medium" },
    b: { zh: "D.塞梅尼斯塔賈", en: "Darja Semenistaja", rank: 102, confidence: "high" } },
  { id: "tn-2048", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:45",
    a: { zh: "朱琳", en: "Lin Zhu", rank: 141, confidence: "high" },
    b: { zh: "拉莫托曼加-拉喬納", en: "Tiantsoa Rakotomanga Rajaonah", rank: 153, confidence: "high" },
    finalResult: { winner: "a", score: "6-2 6-3" } },
  { id: "tn-2011", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:00",
    a: { zh: "露西亞.布隆澤蒂", en: "Lucia Bronzetti", rank: 127, confidence: "high" },
    b: { zh: "J.米庫斯基特", en: "Justina Mikulskyte", rank: 244, confidence: "high" } },
  { id: "tn-2041", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:15",
    a: { zh: "T.科斯托維奇", en: "Teodora Kostovic", rank: 178, confidence: "medium" },
    b: { zh: "R.斯拉姆科娃", en: "Rebecca Sramkova", rank: 136, confidence: "medium" },
    finalResult: { winner: "a", score: "4-6 7-6 6-4" } },
  { id: "tn-2020", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:20",
    note: "安德列斯庫久傷復出 · 排名已掉出榜外、嚴重失真 · 引擎不靠失真排名硬猜 —— 你的判斷值錢。",
    a: { zh: "吉爾.泰克曼", en: "Jil Teichmann", rank: 170, confidence: "high" },
    b: { zh: "比安卡.安德列斯庫", en: "Bianca Andreescu", rank: null, confidence: "low" },
    finalResult: { winner: "b", score: "6-7 6-1 6-4" } },
  { id: "tn-2035", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:20",
    a: { zh: "H.沃特森", en: "Heather Watson", rank: 327, confidence: "high" },
    b: { zh: "T.普雷佐薩娃", en: "Tatiana Prozorova", rank: 172, confidence: "medium" },
    finalResult: { winner: "a", score: "5-7 6-3 7-5" } },
  { id: "tn-2045", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:20",
    a: { zh: "里奧利亞.讓讓", en: "Leolia Jeanjean", rank: 115, confidence: "medium" },
    b: { zh: "E.葛爾格茲", en: "Ekaterine Gorgodze", rank: 169, confidence: "high" } },
  { id: "tn-2006", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:25",
    a: { zh: "白卓璇", en: "Bai Zhuoxuan", rank: 263, confidence: "high" },
    b: { zh: "波琳娜.伊亞琴科", en: "Polina Iatcenko", rank: 163, confidence: "high" },
    finalResult: { winner: "b", score: "7-6 6-2" } },
  { id: "tn-2050", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:25",
    a: { zh: "艾爾維娜.卡列娃", en: "Elvina Kalieva", rank: 135, confidence: "high" },
    b: { zh: "羅賓.蒙哥馬利", en: "Robin Montgomery", rank: 194, confidence: "high" },
    finalResult: { winner: "b", score: "6-2 6-2" } },
  { id: "tn-2039", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:30",
    a: { zh: "克萊維.恩古諾", en: "Clervie Ngounoue", rank: 224, confidence: "medium" },
    b: { zh: "P.庫德梅托娃", en: "Polina Kudermetova", rank: 116, confidence: "high" },
    finalResult: { winner: "b", score: "6-1 6-2" } },
  { id: "tn-2040", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:30",
    a: { zh: "絲托姆.亨特", en: "Storm Hunter", rank: 201, confidence: "medium" },
    b: { zh: "薩諾維奇", en: "Aliaksandra Sasnovich", rank: 109, confidence: "high" } },
  { id: "tn-2044", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:30",
    a: { zh: "V.波德雷茲", en: "Veronika Podrez", rank: 142, confidence: "high" },
    b: { zh: "M.蒂莫菲耶娃", en: "Maria Timofeeva", rank: 92, confidence: "medium" },
    finalResult: { winner: "b", score: "6-4 6-2" } },
  { id: "tn-2024", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:40",
    a: { zh: "A.查拉耶娃", en: "Anastasia Zakharova", rank: 91, confidence: "medium" },
    b: { zh: "卡羅琳.維爾納", en: "Caroline Werner", rank: 242, confidence: "medium" },
    finalResult: { winner: "a", score: "5-7 6-4 6-0" } },
  { id: "tn-2049", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:45",
    a: { zh: "木下晴結", en: "Hayu Kinoshita", rank: 227, confidence: "high" },
    b: { zh: "博爾克瓦澤", en: "Mariam Bolkvadze", rank: 503, confidence: "medium" },
    finalResult: { winner: "b", score: "6-3 6-2" } },
  { id: "tn-2038", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 00:00",
    a: { zh: "本玉真唯", en: "Mai Hontama", rank: 182, confidence: "medium" },
    b: { zh: "阿什琳.克魯格", en: "Ashlyn Krueger", rank: 96, confidence: "high" },
    finalResult: { winner: "b", score: "6-3 5-7 6-3" } },
  { id: "tn-2010", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 00:10",
    a: { zh: "伊莉莎拉.亞內娃", en: "Elizara Yaneva", rank: 201, confidence: "high" },
    b: { zh: "凱蒂.沃利涅", en: "Katie Volynets", rank: 99, confidence: "high" } },
  { id: "tn-2042", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 00:20",
    a: { zh: "巴索里貝菈", en: "Marina Bassols Ribera", rank: 143, confidence: "high" },
    b: { zh: "王曦雨", en: "Wang Xiyu", rank: 86, confidence: "high" } },
  { id: "tn-2051", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25",
    a: { zh: "J.德裡德姆", en: "Jeline Vandromme", rank: null, confidence: "low" },
    b: { zh: "瑪麗亞.卡萊", en: "Maria Lourdes Carle", rank: 148, confidence: "high" },
    finalResult: { winner: "a", score: "6-7 6-4 6-3" } },

  // ── WTA · 伊斯特本公開賽(草地)─────────────────────────────
  { id: "tn-2046", tour: "wta", tournament: "伊斯特本公開賽", surface: "grass", time: "6/24 22:50",
    a: { zh: "金伯莉.比爾賴", en: "Kimberly Birrell", rank: 73, confidence: "high" },
    // 馬琴科原本英文名查不到("?")→ 自動結算靠英文名比對 → 配不到。 Tim 補上 Petra Marcinko +
    //   官方賽果 → 手動結算(手動永遠優先)。 rank 仍留空:賽前沒誠實開盤,不回頭補假引擎線(不進引擎戰績)。
    b: { zh: "P.馬琴科", en: "Petra Marcinko", rank: null, confidence: "low" },
    finalResult: { winner: "b", score: "6-1 6-4" } },

  // ── WTA · 巴特洪堡公開賽(草地)─────────────────────────────
  { id: "tn-2136", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/24 23:00",
    a: { zh: "伊琳娜.貝古", en: "Irina-Camelia Begu", rank: 211, confidence: "high" },
    b: { zh: "卡蘿琳娜.穆霍娃", en: "Karolina Muchova", rank: 11, confidence: "high" },
    finalResult: { winner: "b", score: "6-1 6-1" } },
  { id: "tn-2052", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/25 17:30",
    a: { zh: "絲祿托莉娜", en: "Elina Svitolina", rank: 8, confidence: "high" },
    b: { zh: "王欣瑜", en: "Wang Xinyu", rank: 52, confidence: "high" } },
  { id: "tn-2056", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/25 17:30",
    a: { zh: "葉卡捷琳娜.亞歷山德拉", en: "Ekaterina Alexandrova", rank: 19, confidence: "high" },
    b: { zh: "大坂直美", en: "Naomi Osaka", rank: 15, confidence: "high" } },

  // ── ATP · 普羅夫迪夫挑戰賽(紅土)─────────────────────────────
  { id: "tn-2057", tour: "atp", tournament: "普羅夫迪夫挑戰賽", surface: "clay", time: "6/25 15:30",
    a: { zh: "奧伯寧.米利奇", en: "Ognjen Milic", rank: 359, confidence: "medium" },
    b: { zh: "桑塔馬塔-羅伊格", en: "Andres Santamarta Roig", rank: 712, confidence: "medium" },
    finalResult: { winner: "b", score: "6-0 6-2" } },
  { id: "tn-2060", tour: "atp", tournament: "普羅夫迪夫挑戰賽", surface: "clay", time: "6/25 15:30",
    a: { zh: "托馬索.孔帕紐奇", en: "Tommaso Compagnucci", rank: 398, confidence: "high" },
    b: { zh: "P.內斯特洛夫", en: "Petr Nesterov", rank: 386, confidence: "high" },
    finalResult: { winner: "b", score: "6-3 7-6" } },

  // ── 2026-06-25 · 下一輪(R2)· 兩位都是上一輪晉級、我們已有資料的球員 → 名字/排名沿用前一輪
  //   (運彩中文名一字不改)· 賽果走 ESPN 自動結算(英文名 + 賽事 + 開賽日對帳)。 ──────────────
  // ── ATP · 溫布頓網球公開賽(草地)R2 ──
  { id: "tn-2022", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:10",
    a: { zh: "奧托.維爾塔寧", en: "Otto Virtanen", rank: 130, confidence: "high" },
    b: { zh: "布德科夫-基埃爾", en: "Nicolai Budkov Kjaer", rank: 140, confidence: "medium" } },
  { id: "tn-2025", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:10",
    a: { zh: "坂本怜", en: "Rei Sakamoto", rank: 148, confidence: "high" },
    b: { zh: "J.法里亞", en: "Jaime Faria", rank: 97, confidence: "high" } },
  { id: "tn-2026", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:10",
    a: { zh: "杜尚.拉約維奇", en: "Dusan Lajovic", rank: 131, confidence: "high" },
    b: { zh: "維利烏斯.高巴斯", en: "Vilius Gaubas", rank: 105, confidence: "high" } },
  { id: "tn-2027", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:10",
    a: { zh: "權純雨", en: "Kwon Soon-woo", rank: 202, confidence: "medium" },
    b: { zh: "亞歷杭德羅.莫爾-卡納斯", en: "Alejandro Moro Canas", rank: 233, confidence: "high" },
    finalResult: { winner: "a", score: "6-4 7-6 6-3" } },
  { id: "tn-2028", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:10",
    a: { zh: "基里安.雅凱", en: "Kyrian Jacquet", rank: 146, confidence: "high" },
    b: { zh: "蒂莫菲.史卡托夫", en: "Timofey Skatov", rank: 189, confidence: "medium" } },
  { id: "tn-2013", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 18:00",
    a: { zh: "崔斯坦.博耶", en: "Tristan Boyer", rank: 210, confidence: "medium" },
    b: { zh: "拉馬斯魯伊斯", en: "Pablo Llamas Ruiz", rank: 119, confidence: "high" } },

  // ── ATP · 伊斯特本公開賽(草地)R2 ──
  { id: "tn-2023", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/25 21:30",
    note: "J.德雷珀剛傷退復出 · 排名(#160)嚴重失真 · 引擎不靠失真排名硬猜 —— 這場你的判斷比引擎值錢。",
    a: { zh: "G.迪亞洛", en: "Gabriel Diallo", rank: 91, confidence: "high" },
    b: { zh: "J.德雷珀", en: "Jack Draper", rank: null, confidence: "low" } },

  // ── WTA · 溫布頓網球公開賽(草地)R2 ──
  { id: "tn-2036", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    a: { zh: "朱琳", en: "Lin Zhu", rank: 141, confidence: "high" },
    b: { zh: "T.科斯托維奇", en: "Teodora Kostovic", rank: 178, confidence: "medium" },
    finalResult: { winner: "b", score: "6-3 6-4" } },
  { id: "tn-2037", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    a: { zh: "A.加薩諾娃", en: "Anastasia Gasanova", rank: 210, confidence: "high" },
    b: { zh: "D.塞梅尼斯塔賈", en: "Darja Semenistaja", rank: 102, confidence: "high" } },
  { id: "tn-2047", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    a: { zh: "A.查拉耶娃", en: "Anastasia Zakharova", rank: 91, confidence: "medium" },
    b: { zh: "P.庫德梅托娃", en: "Polina Kudermetova", rank: 116, confidence: "high" },
    finalResult: { winner: "b", score: "4-6 6-4 6-1" } },
  { id: "tn-2029", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    a: { zh: "H.沃特森", en: "Heather Watson", rank: 327, confidence: "high" },
    b: { zh: "M.蒂莫菲耶娃", en: "Maria Timofeeva", rank: 92, confidence: "medium" } },
  { id: "tn-2030", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    a: { zh: "波琳娜.伊亞琴科", en: "Polina Iatcenko", rank: 163, confidence: "high" },
    b: { zh: "阿什琳.克魯格", en: "Ashlyn Krueger", rank: 96, confidence: "high" } },
  { id: "tn-2031", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    a: { zh: "羅賓.蒙哥馬利", en: "Robin Montgomery", rank: 194, confidence: "high" },
    b: { zh: "巴索里貝菈", en: "Marina Bassols Ribera", rank: 143, confidence: "high" } },
  { id: "tn-2032", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    a: { zh: "里奧利亞.讓讓", en: "Leolia Jeanjean", rank: 115, confidence: "medium" },
    b: { zh: "凱蒂.沃利涅", en: "Katie Volynets", rank: 99, confidence: "high" } },
  { id: "tn-2033", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    a: { zh: "露西亞.布隆澤蒂", en: "Lucia Bronzetti", rank: 127, confidence: "high" },
    b: { zh: "莉娜.喬爾切斯卡", en: "Lina Gjorcheska", rank: 188, confidence: "medium" } },
  { id: "tn-2034", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 19:30",
    note: "安德列斯庫久傷復出 · 排名已掉出榜外、嚴重失真 · 引擎不靠失真排名硬猜 —— 你的判斷值錢。",
    a: { zh: "比安卡.安德列斯庫", en: "Bianca Andreescu", rank: null, confidence: "low" },
    b: { zh: "薩諾維奇", en: "Aliaksandra Sasnovich", rank: 109, confidence: "high" } },

  // ── 2026-06-26 · 草地熱身賽主賽事(認得出、ESPN 鏡像收得到的場才上 · 米其林式克制)──────────
  //   會外賽 / 挑戰賽不上(ESPN 鏡像收不到 = 永遠補不到官方賽果);認不出排名的對手也不上。
  //   排名沿用本檔既有 curate(同名同分,賽前一字不改)· 新面孔查現時官方世界排名估種子分。
  //   賽果走 ESPN 自動結算(英文名 + 賽事別名 eastbourne/mallorca/bad homburg + 開賽日對帳)。
  // ── WTA · 巴特洪堡公開賽(草地)R2 · 兩位前一輪都晉級的主賽選手 ──
  { id: "tn-2062", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/26 19:00",
    a: { zh: "大坂直美", en: "Naomi Osaka", rank: 15, confidence: "high" },
    b: { zh: "王欣瑜", en: "Wang Xinyu", rank: 52, confidence: "high" } },
  // ── WTA · 伊斯特本公開賽(草地)· 奧斯塔佩科(賽會3種子)R2 ──
  { id: "tn-2003", tour: "wta", tournament: "伊斯特本公開賽", surface: "grass", time: "6/26 18:00",
    note: "馬莉亞是草地老將(2022 溫網四強)· 引擎只看排名、不懂她的草地專長 → 這場引擎可能低估她,你的判斷值錢。",
    a: { zh: "奧斯塔佩科", en: "Jelena Ostapenko", rank: 28, confidence: "high" },
    b: { zh: "T.馬莉亞", en: "Tatjana Maria", rank: 86, confidence: "medium" } },
  // ── ATP · 馬約卡公開賽(草地)R2 ──
  { id: "tn-2078", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/26 21:00",
    a: { zh: "伊森.奎因", en: "Ethan Quinn", rank: 63, confidence: "medium" },
    b: { zh: "努諾.博爾赫斯", en: "Nuno Borges", rank: 53, confidence: "high" } },
  // ── ATP · 伊斯特本公開賽(草地)· 德雷珀傷退復出排名失真 → 引擎不硬開,照樣可押 ──
  { id: "tn-2000", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/26 22:40",
    note: "J.德雷珀剛傷退復出 · 排名嚴重失真 · 引擎不靠失真排名硬猜 —— 這場你的判斷比引擎值錢。",
    a: { zh: "U.亨伯特", en: "Ugo Humbert", rank: 30, confidence: "high" },
    b: { zh: "J.德雷珀", en: "Jack Draper", rank: null, confidence: "low" } },
  // ── WTA · 巴特洪堡公開賽(草地)準決賽 · 穆霍娃(前段)vs 魯塞 —— 研究查實身分(運彩串流名「卡薩特金娜·穆古」
  //   是亂碼,實為穆霍娃)· 魯塞排名跨源 67-105 → 引擎估中段、confidence medium。 ESPN 收得到 → 自動結算。
  // 🔴 id 加 -0626:運彩場次號會跨日回收(tn-2006 已被 6/24 溫網會外賽用掉)→ 加日期後綴保唯一(對帳走英文名+賽事+日,不靠 id)。
  { id: "tn-2006-0626", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/26 21:00",
    a: { zh: "卡蘿琳娜.穆霍娃", en: "Karolina Muchova", rank: 11, confidence: "high" },
    b: { zh: "埃列娜-加布麗艾拉.魯塞", en: "Elena-Gabriela Ruse", rank: 80, confidence: "medium" } },
  // ── ATP · 普羅夫迪夫挑戰賽(紅土)準決賽 · 研究查實身分+排名(Sofascore 列 6/26 SF)。
  //   🔴 挑戰賽 ESPN 鏡像收不到 → 賽後自動結算對不到、退手動(同其餘挑戰賽 · Tim 賽後 curate)。
  { id: "tn-2061-0626", tour: "atp", tournament: "普羅夫迪夫挑戰賽", surface: "clay", time: "6/26 19:10",
    a: { zh: "蒙特斯-德拉托雷", en: "Inaki Montes-de la Torre", rank: 312, confidence: "medium" },
    b: { zh: "桑塔馬塔-羅伊格", en: "Andres Santamarta Roig", rank: 871, confidence: "medium" } },

  // ── 2026-06-27 · 草地熱身賽決賽 / 末輪(從台灣運彩 6/27 看板 curate · 名字一字不改)──────────
  //   🔴 id 一律加 -0627:運彩場次號跨日回收(2003 已被 6/26 伊斯特本、2010 已被 6/25 溫網用掉)→
  //   全批加日期後綴保唯一(對帳走英文名 + 賽事 + 開賽日,不靠 id · 後綴對 allowlist tn- / auto-settle 無影響)。
  //   多數球員沿用本檔既有 curate(同名同分,賽前一字不改)· 新面孔查現時官方世界排名估種子分。
  //   ESPN 自動結算:巴特洪堡 / 伊斯特本 / 馬約卡(別名已建)· 🔴 普羅夫迪夫挑戰賽 ESPN 收不到 → 退手動(Tim curate)。
  // ── WTA · 巴特洪堡公開賽(草地)決賽 · 大坂直美 vs 穆霍娃 ──
  { id: "tn-2003-0627", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/27 17:00",
    a: { zh: "大坂直美", en: "Naomi Osaka", rank: 15, confidence: "high" },
    b: { zh: "卡蘿莉娜.穆霍娃", en: "Karolina Muchova", rank: 11, confidence: "high" } },
  // ── WTA · 伊斯特本公開賽(草地)· 基斯 vs 馬莉亞(草地老將,引擎只看排名可能低估)──
  { id: "tn-2010-0627", tour: "wta", tournament: "伊斯特本公開賽", surface: "grass", time: "6/27 19:00",
    note: "馬莉亞是草地老將(2022 溫網四強)· 引擎只看排名、不懂她的草地專長 → 這場引擎可能低估她,你的判斷值錢。",
    a: { zh: "基斯", en: "Madison Keys", rank: 7, confidence: "high" },
    b: { zh: "T.馬莉亞", en: "Tatjana Maria", rank: 86, confidence: "medium" } },
  // ── ATP · 馬約卡公開賽(草地)· 達比多維奇 vs 奎因 ──
  { id: "tn-2008-0627", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/27 21:00",
    a: { zh: "達比多維奇", en: "Alejandro Davidovich Fokina", rank: 30, confidence: "high" },
    b: { zh: "伊森.奎因", en: "Ethan Quinn", rank: 63, confidence: "medium" } },
  // ── ATP · 伊斯特本公開賽(草地)· 亨伯特 vs 伯格斯 ──
  { id: "tn-2009-0627", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/27 21:30",
    a: { zh: "U.亨伯特", en: "Ugo Humbert", rank: 30, confidence: "high" },
    b: { zh: "Z.伯格斯", en: "Zizou Bergs", rank: 50, confidence: "high" } },
  // ── ATP · 普羅夫迪夫挑戰賽(紅土)· 科普 vs 蒙特斯-德拉托雷 ──
  //   🔴 桑德羅.科普 = 挑戰賽長尾,查不到可靠排名 → 引擎不硬開假盤(rank null)· 照樣可押。
  //   挑戰賽 ESPN 鏡像收不到 → 賽後自動結算對不到、退手動(Tim 賽後 curate)。
  { id: "tn-2004-0627", tour: "atp", tournament: "普羅夫迪夫挑戰賽", surface: "clay", time: "6/27 22:00",
    note: "桑德羅.科普是挑戰賽長尾,我們查不到可靠排名 · 引擎不硬開假盤 —— 照樣可押,你的判斷比引擎值錢。",
    a: { zh: "桑德羅.科普", en: "Sandro Kopp", rank: null, confidence: "low" },
    b: { zh: "蒙特斯-德拉托雷", en: "Inaki Montes-de la Torre", rank: 312, confidence: "medium" } },
];
