import type { TennisMatch } from "@/lib/tennis/matches";

// ── ZONE 27 · 網球真實賽程資料(2026-06-24/25 · 從台灣運彩 curate · 名字一字不改)──────
// 純資料檔(邏輯在 matches.ts)。 id = 運彩場次編號。 rank = 球員辨識後查「現時官方世界排名」
// (估計種子分來源 · top-60 走官方榜核對、長尾用辨識排名)· 換算引擎勝率。
// 🔴 誠實鐵律落地:
//   · 進行中(live)→ 不開盤(引擎只做賽前)。
//   · 球員認不出 / 排名查不到 → rank null + confidence "low" → 自動「覆蓋建置中」。
//   · 剛傷退復出(德雷珀 #160 / 季米特洛夫 #170 / 安德列斯庫 出榜外)→ 排名嚴重失真,
//     引擎不靠失真排名硬猜 → 標 note,不開盤(這正是「引擎有盲點、你的判斷值錢」)。
// 這些多為溫網會外賽 + 草地熱身賽,球員多在 #90–#260。 結算後 Tim 補 finalResult(Wave 2)。
// ─────────────────────────────────────────────────────

export const TENNIS_DRAW: TennisMatch[] = [
  // ── ATP · 伊斯特本公開賽(草地)─────────────────────────────
  { id: "tn-2061", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/24",
    a: { zh: "J.布魯克斯比", en: "Jenson Brooksby", rank: 67, confidence: "high" },
    b: { zh: "U.亨伯特", en: "Ugo Humbert", rank: 30, confidence: "high" },
    finalResult: { winner: "b", score: "6-3 6-2" } },
  { id: "tn-2180", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/24 22:30",
    a: { zh: "湯瑪斯.馬丁.艾切維利", en: "Tomas Martin Etcheverry", rank: 32, confidence: "high" },
    b: { zh: "G.迪亞洛", en: "Gabriel Diallo", rank: 91, confidence: "high" },
    finalResult: { winner: "b", score: "6-7 6-3 6-2" } },
  { id: "tn-2174", tour: "atp", tournament: "伊斯特本公開賽", surface: "grass", time: "6/24 22:40",
    note: "J.德雷珀剛傷退復出 · 排名(#160)嚴重失真 · 引擎不靠失真排名硬猜 —— 這場你的判斷比引擎值錢。",
    a: { zh: "傑克.平寧頓-瓊斯", en: "Jack Pinnington Jones", rank: 145, confidence: "high" },
    b: { zh: "J.德雷珀", en: "Jack Draper", rank: null, confidence: "low" },
    finalResult: { winner: "b", score: "7-5 6-4" } },

  // ── ATP · 溫布頓網球公開賽(草地 · 多為會外賽)─────────────────
  { id: "tn-2141", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "即將開始",
    a: { zh: "基默.科佩揚斯", en: "Kimmer Coppejans", rank: 212, confidence: "medium" },
    b: { zh: "羅曼.薩菲烏林", en: "Roman Safiullin", rank: 141, confidence: "medium" },
    finalResult: { winner: "b", score: "7-6 7-5" } },
  { id: "tn-2158", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "13 分鐘後開始",
    a: { zh: "蒂莫菲.史卡托夫", en: "Timofey Skatov", rank: 189, confidence: "medium" },
    b: { zh: "埃利亞斯.伊梅爾", en: "Elias Ymer", rank: 191, confidence: "medium" },
    finalResult: { winner: "a", score: "6-4 6-1" } },
  { id: "tn-2138", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "18 分鐘後開始",
    a: { zh: "盧卡.帕夫洛維奇", en: "Luka Pavlovic", rank: 218, confidence: "high" },
    b: { zh: "J.法里亞", en: "Jaime Faria", rank: 97, confidence: "high" },
    finalResult: { winner: "b", score: "6-4 6-4" } },
  { id: "tn-2140", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "18 分鐘後開始",
    a: { zh: "邁克爾.鄭", en: "Michael Zheng", rank: 145, confidence: "medium" },
    b: { zh: "捷雷", en: "Laslo Djere", rank: 205, confidence: "medium" },
    finalResult: { winner: "a", score: "7-5 6-3" } },
  { id: "tn-2156", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "18 分鐘後開始",
    a: { zh: "杜尚.拉約維奇", en: "Dusan Lajovic", rank: 131, confidence: "high" },
    b: { zh: "克里斯.羅德施", en: "Chris Rodesch", rank: 139, confidence: "high" },
    finalResult: { winner: "a", score: "6-2 6-4" } },
  { id: "tn-2166", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "18 分鐘後開始",
    a: { zh: "莫埃茲.埃查爾吉", en: "Moez Echargui", rank: 140, confidence: "high" },
    b: { zh: "基根.史密斯", en: "Keegan Smith", rank: 244, confidence: "high" },
    finalResult: { winner: "a", score: "6-4 3-6 7-6" } },
  { id: "tn-2165", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "23 分鐘後開始",
    a: { zh: "亞瑟.蓋亞", en: "Arthur Gea", rank: 135, confidence: "high" },
    b: { zh: "權純雨", en: "Kwon Soon-woo", rank: 202, confidence: "medium" },
    finalResult: { winner: "b", score: "5-7 6-3 6-4" } },
  { id: "tn-2159", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "27 分鐘後開始",
    a: { zh: "奧托.維爾塔寧", en: "Otto Virtanen", rank: 130, confidence: "high" },
    b: { zh: "盧卡.納迪", en: "Luca Nardi", rank: 151, confidence: "medium" },
    finalResult: { winner: "a", score: "6-4 6-4" } },
  { id: "tn-2167", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "27 分鐘後開始",
    a: { zh: "哈羅德.馬約", en: "Harold Mayot", rank: 214, confidence: "medium" },
    b: { zh: "亞歷杭德羅.莫爾-卡納斯", en: "Alejandro Moro Canas", rank: 233, confidence: "high" },
    finalResult: { winner: "b", score: "6-3 7-6" } },
  { id: "tn-2178", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "27 分鐘後開始",
    a: { zh: "亨利.塞爾", en: "Henry Searle", rank: 263, confidence: "high" },
    b: { zh: "維利烏斯.高巴斯", en: "Vilius Gaubas", rank: 105, confidence: "high" },
    finalResult: { winner: "b", score: "7-6 7-6" } },
  { id: "tn-2164", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:40",
    a: { zh: "基里安.雅凱", en: "Kyrian Jacquet", rank: 146, confidence: "high" },
    b: { zh: "安德里亞.蓋里耶里", en: "Andrea Guerrieri", rank: 229, confidence: "high" },
    finalResult: { winner: "a", score: "7-6 6-4" } },
  { id: "tn-2145", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:50",
    a: { zh: "坂本怜", en: "Rei Sakamoto", rank: 148, confidence: "high" },
    b: { zh: "阿齊茲.杜加茲", en: "Aziz Dougaz", rank: null, confidence: "low" },
    finalResult: { winner: "a", score: "6-4 6-4" } },
  { id: "tn-2172", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:20",
    a: { zh: "馬特.多迪格", en: "Matej Dodig", rank: 201, confidence: "high" },
    b: { zh: "布德科夫-基埃爾", en: "Nicolai Budkov Kjaer", rank: 140, confidence: "medium" },
    finalResult: { winner: "b", score: "6-2 7-6" } },
  { id: "tn-2160", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:45",
    a: { zh: "A.佩萊格里諾", en: "Andrea Pellegrino", rank: 109, confidence: "high" },
    b: { zh: "崔斯坦.博耶", en: "Tristan Boyer", rank: 210, confidence: "medium" },
    finalResult: { winner: "b", score: "6-2 6-1" } },
  { id: "tn-2161", tour: "atp", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:45",
    a: { zh: "馬丁-蒂芬", en: "Pol Martin Tiffon", rank: 220, confidence: "medium" },
    b: { zh: "拉馬斯魯伊斯", en: "Pablo Llamas Ruiz", rank: 119, confidence: "high" },
    finalResult: { winner: "b", score: "6-4 6-2" } },

  // ── ATP · 馬約卡公開賽(草地)─────────────────────────────
  { id: "tn-2190", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/24 23:30",
    note: "季米特洛夫剛傷退復出(外卡)· 排名(#170)嚴重失真 · 引擎不靠失真排名硬猜 —— 你的判斷值錢。",
    a: { zh: "季米特洛夫", en: "Grigor Dimitrov", rank: null, confidence: "low" },
    b: { zh: "阿卜杜拉.謝爾巴耶夫", en: "Abdullah Shelbayh", rank: 259, confidence: "medium" } },
  { id: "tn-2063", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/25 17:00",
    a: { zh: "維特.科普里瓦", en: "Vit Kopriva", rank: 68, confidence: "medium" },
    b: { zh: "伊森.奎因", en: "Ethan Quinn", rank: 63, confidence: "medium" } },
  { id: "tn-2054", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/25 18:10",
    a: { zh: "努諾.博爾赫斯", en: "Nuno Borges", rank: 53, confidence: "high" },
    b: { zh: "盧西亞諾.達德里", en: "Luciano Darderi", rank: 16, confidence: "high" } },
  { id: "tn-2055", tour: "atp", tournament: "馬約卡公開賽", surface: "grass", time: "6/25 20:30",
    a: { zh: "法比安.馬羅森", en: "Fabian Marozsan", rank: 62, confidence: "high" },
    b: { zh: "凱曼諾維奇", en: "Miomir Kecmanovic", rank: 51, confidence: "high" } },

  // ── WTA · 溫布頓網球公開賽(草地 · 多為會外賽)─────────────────
  { id: "tn-2016", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "22 分鐘後開始",
    a: { zh: "埃默生.瓊斯", en: "Emerson Jones", rank: 129, confidence: "medium" },
    b: { zh: "A.加薩諾娃", en: "Anastasia Gasanova", rank: 210, confidence: "high" } },
  { id: "tn-2194", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:30",
    a: { zh: "莉娜.喬爾切斯卡", en: "Lina Gjorcheska", rank: 188, confidence: "medium" },
    b: { zh: "弗朗西斯卡.豪爾赫", en: "Francisca Jorge", rank: 200, confidence: "medium" } },
  { id: "tn-2007", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:35",
    a: { zh: "日比野菜緒", en: "Nao Hibino", rank: 171, confidence: "medium" },
    b: { zh: "D.塞梅尼斯塔賈", en: "Darja Semenistaja", rank: 102, confidence: "high" } },
  { id: "tn-2048", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 22:45",
    a: { zh: "朱琳", en: "Lin Zhu", rank: 141, confidence: "high" },
    b: { zh: "拉莫托曼加-拉喬納", en: "Tiantsoa Rakotomanga Rajaonah", rank: 153, confidence: "high" } },
  { id: "tn-2011", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:00",
    a: { zh: "露西亞.布隆澤蒂", en: "Lucia Bronzetti", rank: 127, confidence: "high" },
    b: { zh: "J.米庫斯基特", en: "Justina Mikulskyte", rank: 244, confidence: "high" } },
  { id: "tn-2041", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:15",
    a: { zh: "T.科斯托維奇", en: "Teodora Kostovic", rank: 178, confidence: "medium" },
    b: { zh: "R.斯拉姆科娃", en: "Rebecca Sramkova", rank: 136, confidence: "medium" },
    finalResult: { winner: "a", score: "4-6 7-6 6-4" } },
  { id: "tn-2020", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:20",
    note: "安德列斯庫久傷復出 · 排名已掉出榜外、嚴重失真 · 引擎不靠失真排名硬猜 —— 你的判斷值錢。",
    a: { zh: "吉爾.泰克曼", en: "Jil Teichmann", rank: 170, confidence: "high" },
    b: { zh: "比安卡.安德列斯庫", en: "Bianca Andreescu", rank: null, confidence: "low" },
    finalResult: { winner: "b", score: "6-7 6-1 6-4" } },
  { id: "tn-2035", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:20",
    a: { zh: "H.沃特森", en: "Heather Watson", rank: 327, confidence: "high" },
    b: { zh: "T.普雷佐薩娃", en: "Tatiana Prozorova", rank: 172, confidence: "medium" },
    finalResult: { winner: "a", score: "5-7 6-3 7-5" } },
  { id: "tn-2045", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:20",
    a: { zh: "里奧利亞.讓讓", en: "Leolia Jeanjean", rank: 115, confidence: "medium" },
    b: { zh: "E.葛爾格茲", en: "Ekaterine Gorgodze", rank: 169, confidence: "high" } },
  { id: "tn-2006", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:25",
    a: { zh: "白卓璇", en: "Bai Zhuoxuan", rank: 263, confidence: "high" },
    b: { zh: "波琳娜.伊亞琴科", en: "Polina Iatcenko", rank: 163, confidence: "high" },
    finalResult: { winner: "b", score: "7-6 6-2" } },
  { id: "tn-2050", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:25",
    a: { zh: "艾爾維娜.卡列娃", en: "Elvina Kalieva", rank: 135, confidence: "high" },
    b: { zh: "羅賓.蒙哥馬利", en: "Robin Montgomery", rank: 194, confidence: "high" },
    finalResult: { winner: "b", score: "6-2 6-2" } },
  { id: "tn-2039", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:30",
    a: { zh: "克萊維.恩古諾", en: "Clervie Ngounoue", rank: 224, confidence: "medium" },
    b: { zh: "P.庫德梅托娃", en: "Polina Kudermetova", rank: 116, confidence: "high" },
    finalResult: { winner: "b", score: "6-1 6-2" } },
  { id: "tn-2040", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:30",
    a: { zh: "絲托姆.亨特", en: "Storm Hunter", rank: 201, confidence: "medium" },
    b: { zh: "薩諾維奇", en: "Aliaksandra Sasnovich", rank: 109, confidence: "high" } },
  { id: "tn-2044", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:30",
    a: { zh: "V.波德雷茲", en: "Veronika Podrez", rank: 142, confidence: "high" },
    b: { zh: "M.蒂莫菲耶娃", en: "Maria Timofeeva", rank: 92, confidence: "medium" },
    finalResult: { winner: "b", score: "6-4 6-2" } },
  { id: "tn-2024", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:40",
    a: { zh: "A.查拉耶娃", en: "Anastasia Zakharova", rank: 91, confidence: "medium" },
    b: { zh: "卡羅琳.維爾納", en: "Caroline Werner", rank: 242, confidence: "medium" } },
  { id: "tn-2049", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/24 23:45",
    a: { zh: "木下晴結", en: "Hayu Kinoshita", rank: 227, confidence: "high" },
    b: { zh: "博爾克瓦澤", en: "Mariam Bolkvadze", rank: 503, confidence: "medium" },
    finalResult: { winner: "b", score: "6-3 6-2" } },
  { id: "tn-2038", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 00:00",
    a: { zh: "本玉真唯", en: "Mai Hontama", rank: 182, confidence: "medium" },
    b: { zh: "阿什琳.克魯格", en: "Ashlyn Krueger", rank: 96, confidence: "high" },
    finalResult: { winner: "b", score: "6-3 5-7 6-3" } },
  { id: "tn-2010", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 00:10",
    a: { zh: "伊莉莎拉.亞內娃", en: "Elizara Yaneva", rank: 201, confidence: "high" },
    b: { zh: "凱蒂.沃利涅", en: "Katie Volynets", rank: 99, confidence: "high" } },
  { id: "tn-2042", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25 00:20",
    a: { zh: "巴索里貝菈", en: "Marina Bassols Ribera", rank: 143, confidence: "high" },
    b: { zh: "王曦雨", en: "Wang Xiyu", rank: 86, confidence: "high" } },
  { id: "tn-2051", tour: "wta", tournament: "溫布頓網球公開賽", surface: "grass", time: "6/25",
    a: { zh: "J.德裡德姆", en: "?", rank: null, confidence: "low" },
    b: { zh: "瑪麗亞.卡萊", en: "Maria Lourdes Carle", rank: 148, confidence: "high" } },

  // ── WTA · 伊斯特本公開賽(草地)─────────────────────────────
  { id: "tn-2046", tour: "wta", tournament: "伊斯特本公開賽", surface: "grass", time: "6/24 22:50",
    a: { zh: "金伯莉.比爾賴", en: "Kimberly Birrell", rank: 73, confidence: "high" },
    b: { zh: "P.馬琴科", en: "?", rank: null, confidence: "low" } },

  // ── WTA · 巴特洪堡公開賽(草地)─────────────────────────────
  { id: "tn-2136", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/24 23:00",
    a: { zh: "伊琳娜.貝古", en: "Irina-Camelia Begu", rank: 211, confidence: "high" },
    b: { zh: "卡蘿琳娜.穆霍娃", en: "Karolina Muchova", rank: 11, confidence: "high" },
    finalResult: { winner: "b", score: "6-1 6-1" } },
  { id: "tn-2052", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/25 17:30",
    a: { zh: "絲祿托莉娜", en: "Elina Svitolina", rank: 8, confidence: "high" },
    b: { zh: "王欣瑜", en: "Wang Xinyu", rank: 52, confidence: "high" } },
  { id: "tn-2056", tour: "wta", tournament: "巴特洪堡公開賽", surface: "grass", time: "6/25 17:30",
    a: { zh: "葉卡捷琳娜.亞歷山德拉", en: "Ekaterina Alexandrova", rank: 19, confidence: "high" },
    b: { zh: "大坂直美", en: "Naomi Osaka", rank: 15, confidence: "high" } },

  // ── ATP · 普羅夫迪夫挑戰賽(紅土)─────────────────────────────
  { id: "tn-2057", tour: "atp", tournament: "普羅夫迪夫挑戰賽", surface: "clay", time: "6/25 15:30",
    a: { zh: "奧伯寧.米利奇", en: "Ognjen Milic", rank: 359, confidence: "medium" },
    b: { zh: "桑塔馬塔-羅伊格", en: "Andres Santamarta Roig", rank: 712, confidence: "medium" } },
  { id: "tn-2060", tour: "atp", tournament: "普羅夫迪夫挑戰賽", surface: "clay", time: "6/25 15:30",
    a: { zh: "托馬索.孔帕紐奇", en: "Tommaso Compagnucci", rank: 398, confidence: "high" },
    b: { zh: "P.內斯特洛夫", en: "Petr Nesterov", rank: 386, confidence: "high" } },
];
