// ── ZONE 27 · Command Palette Index ─────────────────────
// PRIMARY routes only · ~26 → 38 entries · power-user search · Hick's Law-aware
// editorial priority。 Secondary routes accessed via /transparency aggregator
// + Footer + parent-page cross-links(e.g. /founders/* sub-pages 從 /founders
// 探索 · /letter + /year-zero + /heritage + /hey-tim + /annual 從 /transparency
// aggregator · /methodology/diff 從 /methodology · /receipts/* 從 /track-record ·
// /member/calibration + /member/submit 從 /member · /engine-log direct since R120 W5)。
// (/poster + /auth/* intentionally NOT indexed · 同 framing。)
// R122 W1 · /admin 從 「NOT indexed」 改 indexed · per founder-dogfood-canary
// 第 N 次 fire · designer 需要 1-click access to tier preview · per
// [[feedback-zone27-tier-dogfood-method]] memory · client-side spoofable BUT 0
// risk(R113 W1 Kerckhoffs')· /admin still noindex on Vercel(meta robots)·
// 但 Cmd-K visible for designer。

export type CommandItem = {
  label: string;
  /** Short English / mono kicker shown above label · disambiguates */
  kicker: string;
  /** Route path (internal) or full URL (external · opens new tab) */
  path: string;
  /** Group label · controls section ordering in palette */
  group:
    | "入門"
    | "賽事 · 引擎"
    | "品牌 IP"
    | "信任文件"
    | "轉換"
    | "工具 · 外部";
  /** Searchable aliases · Chinese + English + abbrev */
  keywords?: string[];
  external?: boolean;
};

export const COMMAND_ITEMS: CommandItem[] = [
  // ── 入門 ───────────────────────────────────────────
  {
    label: "首頁 · ZONE 27 主入口",
    kicker: "/",
    path: "/",
    group: "入門",
    keywords: ["home", "zone 27", "hero", "首頁", "主頁"],
  },
  {
    label: "5 分鐘入門",
    kicker: "/learn",
    path: "/learn",
    group: "入門",
    keywords: ["learn", "primer", "bill james", "入門", "新手", "introduction"],
  },
  {
    label: "FAQ · 誠實回答",
    kicker: "/faq",
    path: "/faq",
    group: "入門",
    keywords: ["faq", "questions", "常見問題", "問與答"],
  },
  {
    label: "關於 · 品牌方法論",
    kicker: "/about",
    path: "/about",
    group: "入門",
    keywords: ["about", "story", "關於"],
  },
  {
    label: "用語表 · 27 stats + 5 Z27 LEXICON · 32 entries",
    kicker: "/glossary",
    path: "/glossary",
    group: "入門",
    keywords: [
      "glossary",
      "用語",
      "用語表",
      "stat",
      "stats",
      "lexicon",
      "wrc+",
      "woba",
      "fip",
      "babip",
      "ops",
      "whip",
      "sample debt",
      "proved",
      "diverged",
      "z27 lexicon",
      "縮寫",
      "字典",
      "詞彙",
      "看不懂",
      "什麼意思",
    ],
  },

  // ── 賽事 · 引擎 ────────────────────────────────────
  {
    label: "今日賽事板 · CPBL",
    kicker: "/matches",
    path: "/matches",
    group: "賽事 · 引擎",
    keywords: [
      "matches",
      "cpbl",
      "今日賽事",
      "賽程",
      "板",
      "今晚",
      "下午",
      "比賽",
      "戰況",
      "賽況",
      "對戰",
      "對戰組合",
      "戰報",
      "看球",
      "選邊",
      "誰贏",
      "今晚誰贏",
      "預測",
      "賽前",
      "盤口",
      // R115 W2 · Tim 2026-05-25 dogfood「在哪裡可以分享、推薦賽事? 找不到呀!」
      // /matches/[gameId] 內 UserPredictionPicker + AnonPickWidget + ReceiptForwardButton
      // 都 ship 但 share/predict 動作 keywords 之前不 surface · 加 keyword sets
      // 讓 Cmd-K 搜索「分享」「我也猜」「投票」「推薦」 都能找到 → /matches。
      "分享",
      "share",
      "我也猜",
      "您也猜",
      "猜輸贏",
      "投票",
      "推薦",
      "recommend",
      "贏家",
      "黑馬",
      "AnonPick",
      "UserPrediction",
      // R137 W6 · 場館暱稱 + 季事關鍵詞 per Agent C 球迷 slang gap audit
      // (filtered to brand-IP-fit only · CPBL fan audience grammar per
      // [[feedback-zone27-audience-fans-not-engineers]])
      "洲際",
      "天母",
      "新莊",
      "澄清湖",
      "場館",
      "球場",
      "主場",
      "客場",
      "台灣大賽",
      "季後賽",
      "明星賽",
      "總冠軍",
    ],
  },
  {
    label: "MLB · 即時資料",
    kicker: "/matches/mlb",
    path: "/matches/mlb",
    group: "賽事 · 引擎",
    keywords: ["mlb", "美國職棒", "即時", "stats api"],
  },
  {
    label: "即時引擎 · 模擬實驗室",
    kicker: "/lab",
    path: "/lab",
    group: "賽事 · 引擎",
    keywords: [
      "lab",
      "engine",
      "simulator",
      "蒙地卡羅",
      "引擎",
      "模擬",
      "勝率",
      "預測",
      "誰贏",
      "推算",
      "演算",
      "勝負",
      "賠率",
      "monte carlo",
    ],
  },
  {
    label: "自訂實驗室 · Power User",
    kicker: "/lab/custom",
    path: "/lab/custom",
    group: "賽事 · 引擎",
    keywords: ["custom", "power", "自訂", "投手", "pitcher"],
  },
  {
    label: "每日量化早報",
    kicker: "/signal-board",
    path: "/signal-board",
    group: "賽事 · 引擎",
    keywords: [
      "signal",
      "board",
      "早報",
      "daily",
      "brief",
      "晨報",
      "賽前情報",
      "頭條",
      "今日重點",
      "戰況預覽",
      // R137 W6 · 季事關鍵詞 per Agent C 球迷 slang gap audit · seasonal
      // urgency events · 春訓 to 台灣大賽 全年 calendar coverage
      "春訓",
      "開幕戰",
      "常規賽",
      "季中",
      "季末",
      "台灣大賽",
      "季後賽",
      "明星賽",
    ],
  },
  {
    label: "CPBL 投手排行 · 6 stat tabs · URL-shareable",
    kicker: "/cpbl-pitchers",
    path: "/cpbl-pitchers",
    group: "賽事 · 引擎",
    keywords: [
      "cpbl pitchers",
      "排行",
      "leaderboard",
      "投手",
      "pitchers",
      "k9",
      "bb9",
      "hr9",
      "whip",
      "era",
      "ip",
      "stat",
      "ranking",
      "baseball savant",
      "savant",
      "ace",
      "control",
      "波球",
      "勝投",
      "防禦率",
      "三振",
      "保送",
      "王牌",
      "頭號投手",
      "頂尖",
      "球速",
      "球威",
      "速球",
      "變化球",
      "牛棚",
      "終結者",
      "守護神",
      "救援",
      "先發",
      "中繼",
      "外籍投手",
      "洋投",
      "本土投手",
      "球員卡",
      "球員數據",
      "進階數據",
      "進階指標",
      "trackman",
      "advanced",
      // R137 W6 · 投手 archetype 球迷 slang per Agent C · CPBL/Asian baseball
      // 文化 reference · 火球男 = fastball specialist · 控球魔術師 = command
      // specialist · brand IP fit per [[feedback-zone27-audience-fans-not-engineers]]
      "火球男",
      "火球",
      "控球魔術師",
      "控球",
      "魔術師",
      "怪力男",
      "養生球路",
      "肩傷",
      "復出",
      "球速王",
    ],
  },
  {
    label: "CPBL 6 隊伍 投手 aggregation · 球迷 tribal home base",
    kicker: "/cpbl-teams",
    path: "/cpbl-teams",
    group: "賽事 · 引擎",
    keywords: [
      "cpbl teams",
      "teams",
      "隊伍",
      "球團",
      "team page",
      "tribal",
      "統一獅",
      "中信兄弟",
      "富邦悍將",
      "樂天桃猿",
      "味全龍",
      "台鋼雄鷹",
      "lions",
      "brothers",
      "guardians",
      "monkeys",
      "dragons",
      "hawks",
      "獅迷",
      "象迷",
      "兄弟象",
      "兄迷",
      "悍將",
      "猿迷",
      "桃猿",
      "龍迷",
      "鷹迷",
      "鋼鷹",
      "雄鷹",
      "魔猴",
      "球迷",
      "鄉民",
      "支持的球隊",
      "母隊",
      // R137 W6 · 場館暱稱 per Agent C 球迷 slang gap audit · CPBL ballpark
      // affinity = team loyalty hinge · brand IP fit per
      // [[feedback-zone27-audience-fans-not-engineers]]
      "洲際",
      "天母",
      "新莊",
      "澄清湖",
      "場館",
      "球場",
      "主場",
    ],
  },

  // ── 品牌 IP ────────────────────────────────────────
  {
    label: "倒置宣言 · 4 個刻意倒置",
    kicker: "/manifesto",
    path: "/manifesto",
    group: "品牌 IP",
    keywords: ["manifesto", "倒置", "inversion", "philosophy", "宣言"],
  },
  {
    label: "鐵律 · Buffett · Musk · Costco · Jobs 共識",
    kicker: "/discipline",
    path: "/discipline",
    group: "品牌 IP",
    keywords: ["discipline", "鐵律", "buffett", "musk", "costco", "jobs"],
  },
  {
    label: "公開路線圖 · 含「永遠不做」清單",
    kicker: "/roadmap",
    path: "/roadmap",
    group: "品牌 IP",
    keywords: ["roadmap", "路線圖", "未來", "永遠不做"],
  },
  {
    label: "Now · craft journal · SHIPPED / DISCOVERED / UNRESOLVED",
    kicker: "/now",
    path: "/now",
    group: "品牌 IP",
    keywords: ["now", "現在", "craft", "journal", "本週", "工藝"],
  },
  {
    label: "Changelog · git source of truth",
    kicker: "/changelog",
    path: "/changelog",
    group: "品牌 IP",
    keywords: ["changelog", "版本", "git", "歷史", "log"],
  },
  {
    // R128 W2 · NEW /heritage direct Cmd-K entry · per R127 W2 NEW DELTA-of-
    // CPBL positioning section ship · 之前 only via /transparency aggregator
    // 2-click path · 現在 power-user 搜「DELTA」/「Patek Generations」/
    // 「inheritance」/「二代目」/「世代」/「下一代」/「heritage」 直接 jump ·
    // per [[feedback-zone27-delta-of-cpbl-positioning]] memory SOP canonical
    // placement + [[feedback-zone27-tier-dogfood-method]] pattern(同 R122 W1
    // /admin direct-add precedent · 信任文件 / 品牌 IP groups 適當 expansion)。
    label: "Heritage · 替下一個 CPBL 球迷世代守 · DELTA-of-CPBL positioning",
    kicker: "/heritage",
    path: "/heritage",
    group: "品牌 IP",
    keywords: [
      "heritage",
      "繼承",
      "傳承",
      "世代",
      "下一代",
      "二代目",
      "二代目ファン",
      "inheritance",
      "patek",
      "patek philippe",
      "generations",
      "1996",
      "belk",
      "belk 1988",
      "extended self",
      "weinstein 1963",
      "altercasting",
      "delta",
      "delta of cpbl",
      "delta japan",
      "rebas",
      "rebas tw",
      "野球革命",
      "first mover",
      "positioning",
      "category",
      "one-winner-take-all",
      "asian baseball analytics",
      "hanshin tigers",
      "tigers",
    ],
  },

  // ── 信任文件 ───────────────────────────────────────
  {
    label: "Transparency · 完整 audit 一頁可見 · aggregator",
    kicker: "/transparency",
    path: "/transparency",
    group: "信任文件",
    keywords: [
      "transparency",
      "audit",
      "aggregator",
      "anthropic",
      "limits",
      "never",
      "公開",
      "稽核",
    ],
  },
  {
    // R120 W5 · /engine-log direct Cmd-K entry · 之前 only via /transparency
    // aggregator 2-click path · R120 W3 加 LIVE STATE 8-cell Plausible numeric
    // dashboard 後 /engine-log 升 top-tier brand IP signal · 1-click 直達 better
    // 配合 Tim「讓網站熱銷」 mandate · 37/36 entries marginal Hick's Law cost。
    label: "Engine Log · operational artifact + LIVE STATE numeric dashboard",
    kicker: "/engine-log",
    path: "/engine-log",
    group: "信任文件",
    keywords: [
      "engine log",
      "engine-log",
      "ops",
      "operational",
      "status",
      "live state",
      "live status",
      "dashboard",
      "stripe status",
      "cloudflare postmortem",
      "tailscale",
      "plausible",
      "berkshire",
      "summary",
      "numeric",
      "stats",
      "現況",
      "狀態",
      "引擎運轉",
      "operations",
      "uptime",
    ],
  },
  {
    label: "Model Report · 引擎範圍 + 揭露哲學",
    kicker: "/audit",
    path: "/audit",
    group: "信任文件",
    keywords: ["audit", "model", "report", "稽核"],
  },
  {
    label: "技術白皮書 · GitHub 程式碼",
    kicker: "/methodology",
    path: "/methodology",
    group: "信任文件",
    keywords: ["methodology", "技術", "白皮書", "whitepaper"],
  },
  {
    label: "公開戰績 · PROVED vs DIVERGED ledger",
    kicker: "/track-record",
    path: "/track-record",
    group: "信任文件",
    keywords: [
      "track",
      "record",
      "戰績",
      "proved",
      "diverged",
      "ledger",
      "準不準",
      "對了",
      "錯了",
      "命中",
      "Brier",
      "中沒中",
      "命中率",
      "準度",
      "歷史紀錄",
      "對錯",
      "對中",
      "預測紀錄",
      "賭神",
      "報明牌",
      "誰才是神",
    ],
  },
  {
    label: "Calibration · epistemic mirror · reliability diagram",
    kicker: "/calibration",
    path: "/calibration",
    group: "信任文件",
    keywords: ["calibration", "brier", "校準", "538", "tetlock"],
  },
  {
    label: "Integrity · 22 永久不會變 · Berkshire 1996",
    kicker: "/integrity",
    path: "/integrity",
    group: "信任文件",
    keywords: [
      "integrity",
      "誠信",
      "berkshire",
      "buffett",
      "22 binding",
      "redlines",
      "ethics",
      "binding rules",
      "承諾",
      "保證",
      "不會變",
      "永遠",
    ],
  },
  {
    label: "Interact · 10 reader↔writer channels · one-way by design",
    kicker: "/interact",
    path: "/interact",
    group: "信任文件",
    keywords: [
      "interact",
      "互動",
      "討論",
      "討論區",
      "留言板",
      "comment",
      "forum",
      "community",
      "社群",
      "推薦賽事",
      "分享",
      "share",
      "推薦",
      "talk",
      "talk to tim",
      "聊天",
      "chat",
      "互相",
      "彼此",
      "其他人",
      "球迷區",
      "讀者",
      "reader",
      "writer",
      "single voice",
      "stratechery",
      "bill james",
      "hey bill",
      "delta japan",
      "one-way",
      "10 channels",
      "投稿",
      "submit",
      "申請",
      "意見",
      "feedback",
      "為什麼沒有",
      "沒有 community",
      "沒有 forum",
      "沒有討論區",
      "在哪",
      "where",
    ],
  },
  {
    label: "Ethics · 9 binding NOT-DO commitments",
    kicker: "/ethics",
    path: "/ethics",
    group: "信任文件",
    keywords: ["ethics", "policy", "倫理", "承諾", "stratechery", "binding"],
  },
  {
    label: "Steelman · 反 ZONE 27 最強 6 個論證",
    kicker: "/steelman",
    path: "/steelman",
    group: "信任文件",
    keywords: [
      "steelman",
      "objection",
      "反方",
      "論證",
      "pratfall",
      // R109 W5 · LLM / Quark NBA / AI 對立面 keywords 指 Objection #06(R108 W7)·
      // 搜「為什麼不用 AI」 / 「Quark」 / 「LLM」 / 「ChatGPT」 → 直接跳 /steelman ·
      // brand IP「LLM hallucination ≠ deterministic Monte Carlo」 positioning surface。
      "llm",
      "ai 對話",
      "ai 看球",
      "ai 助手",
      "quark",
      "夸克",
      "千问",
      "chatgpt",
      "gpt",
      "claude",
      "豆包",
      "deepseek",
      "為什麼不用 AI",
      "為什麼不用 LLM",
      "natural language",
      "自然語言",
      "多模態",
      "multimodal",
    ],
  },
  {
    label: "覆蓋範圍 · NEVER 清單",
    kicker: "/coverage",
    path: "/coverage",
    group: "信任文件",
    keywords: ["coverage", "覆蓋", "範圍", "scope", "never"],
  },
  {
    label: "隱私政策 · 0 trackers",
    kicker: "/privacy",
    path: "/privacy",
    group: "信任文件",
    keywords: ["privacy", "隱私", "tracker", "cookie", "ga", "pixel"],
  },
  {
    label: "服務條款",
    kicker: "/terms",
    path: "/terms",
    group: "信任文件",
    keywords: ["terms", "條款", "tos", "service"],
  },

  // ── 轉換 ───────────────────────────────────────────
  {
    label: "Founders 27 · 創始終身 · 限量 270 預售",
    kicker: "/founders",
    path: "/founders",
    group: "轉換",
    keywords: [
      "founders",
      "創始",
      "創始會員",
      "27",
      "lifetime",
      "終身",
      "2700",
      "270",
      "贊助",
      "支持",
      "入主",
      "限量",
      "席位",
      "席次",
      "終身會員",
      "ico",
      "天使",
      "patreon",
    ],
  },
  {
    label: "申請 Founders 27 · Patek-style · Tim 親手 review",
    kicker: "/founders/apply",
    path: "/founders/apply",
    group: "轉換",
    keywords: [
      "apply",
      "application",
      "申請",
      "founders",
      "patek",
      "申請表",
      "submit",
    ],
  },
  {
    label: "THE 27 WALL · 270 創始席位視覺化",
    kicker: "/leaderboard",
    path: "/leaderboard",
    group: "轉換",
    keywords: [
      "leaderboard",
      "wall",
      "27 wall",
      "the 27 wall",
      "席位",
      "牆",
      "270",
      "席次",
      "seat",
      "seats",
      "排行",
      "founders wall",
      "誰是創始",
      "誰是 founder",
      "creator wall",
      "看誰在",
    ],
  },
  {
    label: "Open Allocation Ledger · 公開拒絕原因 · 4 axiom",
    kicker: "/founders/ledger",
    path: "/founders/ledger",
    group: "轉換",
    keywords: [
      "ledger",
      "allocation",
      "open allocation",
      "refusal",
      "refusals",
      "拒絕",
      "拒絕原因",
      "rejection",
      "rejected",
      "approval",
      "approval rate",
      "通過率",
      "weekly review",
      "review log",
      "patek",
      "hermes",
      "tesla",
      "process transparency",
      "我會被拒絕嗎",
      "誰被拒絕",
      "為什麼被拒",
    ],
  },
  {
    label: "會員制 · 4-tier ladder 總覽",
    kicker: "/membership",
    path: "/membership",
    group: "轉換",
    keywords: [
      "會員",
      "membership",
      "tier",
      "ladder",
      "訂閱",
      "免費",
      "free",
    ],
  },
  {
    label: "BLACK CARD · CPBL 季票 · ≈ NT$ 6/場",
    kicker: "/membership/black-card",
    path: "/membership/black-card",
    group: "轉換",
    keywords: [
      "black card",
      "blackcard",
      "subscribe",
      "訂閱",
      "黑卡",
      "季票",
      "season pass",
      "1500",
    ],
  },
  {
    // R128 W1 · keywords augment · per R125-R127 §07 PRECEDENT BENCHMARKS
    // 12-fact data table ship · power-user 搜「為何 NT$ 2,700」/「Defector」/
    // 「Stratechery」/「CPBLTV」/「Patek Generations」/「DELTA」/「權證小哥」/etc
    // 直接 jump /pricing/why · 不再 only via「定價/pricing」 narrow keyword·
    // per [[feedback-zone27-paid-model-is-support-not-features]] memory +
    // [[feedback-zone27-delta-of-cpbl-positioning]] memory + R126 TW market
    // agent verified web research data。
    label: "為什麼 NT$ 1,500/season / NT$ 2,700 · 12-fact precedent benchmarks",
    kicker: "/pricing/why",
    path: "/pricing/why",
    group: "轉換",
    keywords: [
      "pricing",
      "why",
      "為什麼",
      "為何",
      "定價",
      "price",
      "1500",
      "2700",
      "math",
      // R128 W1 · §07 PRECEDENT BENCHMARKS 12 facts data brand names
      "defector",
      "stratechery",
      "ben thompson",
      "404 media",
      "kickstarter",
      "fangraphs",
      "hami",
      "hami video",
      "cpbltv",
      "cpbl tv",
      "patek",
      "patek philippe",
      "generations",
      "delta",
      "delta japan",
      "1.02",
      "essence of baseball",
      "yusuke okada",
      "bill james",
      "權證小哥",
      "pressplay",
      "costly signaling",
      "spence 1973",
      "precedent",
      "benchmark",
      "為何要付錢",
      "誰要付錢",
      "支持",
      "support",
      "fund tim",
      "identity tier",
      "patek-tier",
      "270 seats",
      "lifetime",
      "終身",
      "founding subscriber",
    ],
  },

  // ── 工具 · 外部 ────────────────────────────────────
  {
    label: "Member · 您的引擎時間軸",
    kicker: "/member",
    path: "/member",
    group: "工具 · 外部",
    keywords: ["member", "dashboard", "會員頁", "個人", "時間軸"],
  },
  {
    label: "Login · Email + 密碼 註冊 · FREE TIER",
    kicker: "/login",
    path: "/login",
    group: "工具 · 外部",
    keywords: [
      "login",
      "登入",
      "註冊",
      "register",
      "signup",
      "password",
      "密碼",
      "email",
      "auth",
    ],
  },
  {
    label: "GitHub · 完整原始碼開源",
    kicker: "github.com/Tim-xuan-you/zone27-web",
    path: "https://github.com/Tim-xuan-you/zone27-web",
    group: "工具 · 外部",
    keywords: ["github", "source", "code", "原始碼", "open source", "mit"],
    external: true,
  },
  {
    // R122 W1 · Tim 第 N 次 founder-dogfood-canary fire(R36 / R47 / R60 / R113 / R122)
    // 問「設計者怎麼切換 tier 方案?」 · 此非 missing feature · 是 discoverability bug ·
    // /admin AdminTierSwitcher + PreviewModeBanner + Cmd+Shift+P + URL deep link 4 個 entry
    // points 全 ship since R36 W-D · 但 Tim 仍 forget · 加 Cmd-K entry 1-click 可達 ·
    // per [[feedback-zone27-tier-dogfood-method]] memory codify · DO NOT rebuild · DO NOT
    // create separate accounts · ONLY surface existing infrastructure。 安全:per R113 W1
    // Kerckhoffs' principle · client-side spoofable but 0 risk · 0 paid features built。
    label: "🎭 Designer · 切換 tier preview(設計者 dogfood 工具)",
    kicker: "/admin",
    path: "/admin",
    group: "工具 · 外部",
    keywords: [
      "admin",
      "tier",
      "切換",
      "preview",
      "dogfood",
      "設計者",
      "designer",
      "anonymous",
      "free",
      "black",
      "founders",
      "切到 black",
      "切到 founders",
      "切到 free",
      "切到 anonymous",
      "tier switcher",
      "預覽",
      "身份切換",
      "視角",
      "方案",
      "看 BLACK CARD",
      "看 FREE TIER",
      "看訪客",
      "看 Founders",
      "cmd shift p",
      "ctrl shift p",
      "keyboard shortcut",
    ],
  },
];

/** Group display order — palette renders headers in this sequence. */
export const COMMAND_GROUP_ORDER = [
  "入門",
  "賽事 · 引擎",
  "品牌 IP",
  "信任文件",
  "轉換",
  "工具 · 外部",
] as const;

/** Returns filtered items matching the query (case-insensitive substring). */
export function filterCommandItems(
  query: string,
  items: CommandItem[] = COMMAND_ITEMS
): CommandItem[] {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) return items;
  return items.filter((item) => {
    if (item.label.toLowerCase().includes(trimmed)) return true;
    if (item.kicker.toLowerCase().includes(trimmed)) return true;
    if (item.path.toLowerCase().includes(trimmed)) return true;
    if (
      item.keywords?.some((k) => k.toLowerCase().includes(trimmed))
    ) {
      return true;
    }
    return false;
  });
}
